def build_system_prompt():

    return """

The response must contain each requested section exactly once.
Do not repeat NEXT_STEPS.
Do not repeat REASSESSMENT_TRIGGERS.
Do not repeat any JSON field.
You are MoneyBuddy AI, an AI Chief Financial Officer
for individuals.

Your role is to explain and personalize financial decisions
generated by the MoneyBuddy financial engine.

IMPORTANT:

The MoneyBuddy Python financial engine is the source of truth.

You MUST NOT:

- change financial allocations
- change financial priorities
- invent financial numbers
- invent expenses
- invent income
- invent debt terms
- invent investment returns
- promise investment returns
- create unsupported financial products
- contradict the investment decision
- contradict the decision engine
- change scenario results
- invent scenario results

You MAY:

- explain why a decision was made
- personalize the explanation
- explain trade-offs
- summarize the financial situation
- compare supplied What-If scenarios
- explain what the user should do next
- explain when the plan should be reassessed

If information is unavailable, say that it is unavailable.

Never treat past market performance as a guarantee of
future returns.

Do not describe debt repayment as a guaranteed investment
return. Explain it as potentially reducing future interest
costs, subject to the loan terms.

The Python engine calculates financial numbers.
You explain those numbers.

RETURN FORMAT:

You MUST return valid JSON only.

Do not use Markdown.

Do not use code fences.

The JSON must contain exactly these fields:

{
    "headline": "short CFO headline",
    "financial_status": "short description of financial condition",

    "top_priority": {
        "category": "category",
        "action": "action",
        "amount": 0,
        "reason": "reason"
    },

    "secondary_priorities": [
        {
            "category": "category",
            "action": "action",
            "amount": 0,
            "reason": "reason"
        }
    ],

    "investment_status": "status",
    "investment_amount": 0,
    "investment_reason": "reason",

    "goal_status": "status",
    "goal_shortfall": 0,

    "why": [
        "reason 1",
        "reason 2"
    ],

    "next_steps": [
        "step 1",
        "step 2",
        "step 3"
    ],

    "reassessment_triggers": [
        "trigger 1",
        "trigger 2"
    ],

    "personal_message": "short personalized message"
}

The numeric values must come from the supplied MoneyBuddy
financial data.

Do not calculate new allocations.

Do not add fields that are not requested.

Do not output a What-If scenario number unless it was
supplied by the MoneyBuddy Python engine.
"""


def build_user_prompt(
    user,
    health_advice,
    salary_plan,
    goal_analysis,
    market_analysis,
    investment_decision,
    decisions,
    risk_profile=None,
    goal_priorities=None,
    portfolio_recommendation=None,
    scenario=None,
    what_if_scenarios=None
):

    # =====================================================
    # 1. DEFAULT VALUES
    # =====================================================

    if goal_priorities is None:
        goal_priorities = []

    if what_if_scenarios is None:
        what_if_scenarios = []

    # =====================================================
    # 2. BUILD PRIORITY DECISION TEXT
    # =====================================================

    decision_text = ""

    for decision in decisions:

        decision_text += f"""
Priority: {decision.priority}
Category: {decision.category}
Action: {decision.action}
Recommended Amount: ₹{decision.recommended_amount:.2f}
Allocated Amount: ₹{decision.allocated_amount:.2f}
Reason: {decision.reason}
Confidence: {decision.confidence:.1f}%

"""

    # =====================================================
    # 3. BUILD GOAL PRIORITY TEXT
    # =====================================================

    goal_priorities_text = ""

    for goal in goal_priorities:

        goal_priorities_text += f"""
Goal: {goal.name}
Priority Score: {goal.priority_score:.2f}
Urgency: {goal.urgency}
Recommended Focus: {goal.recommended_focus}
Reason: {goal.reason}

"""

    # =====================================================
    # 4. RISK PROFILE
    # =====================================================

    risk_capacity = (
        risk_profile.risk_capacity
        if risk_profile
        else "N/A"
    )

    risk_tolerance = (
        risk_profile.risk_tolerance
        if risk_profile
        else "N/A"
    )

    overall_profile = (
        risk_profile.overall_profile
        if risk_profile
        else "N/A"
    )

    emergency_months = (
        risk_profile.emergency_months
        if risk_profile
        else 0.0
    )

    risk_explanation = (
        risk_profile.explanation
        if risk_profile
        else "N/A"
    )

    # =====================================================
    # 5. PORTFOLIO RECOMMENDATION
    # =====================================================

    port_action = (
        portfolio_recommendation.action
        if portfolio_recommendation
        else "N/A"
    )

    port_priority = (
        portfolio_recommendation.priority
        if portfolio_recommendation
        else "N/A"
    )

    port_reason = (
        portfolio_recommendation.reason
        if portfolio_recommendation
        else "N/A"
    )

    # =====================================================
    # 6. CURRENT SCENARIO
    # =====================================================

    scen_name = (
        scenario.scenario_name
        if scenario
        else "N/A"
    )

    scen_income = (
        scenario.monthly_income
        if scenario
        else 0.0
    )

    scen_expenses = (
        scenario.monthly_expenses
        if scenario
        else 0.0
    )

    scen_surplus = (
        scenario.monthly_surplus
        if scenario
        else 0.0
    )

    scen_debt_pmt = (
        scenario.debt_payment
        if scenario
        else 0.0
    )

    scen_inv_cap = (
        scenario.investment_capacity
        if scenario
        else 0.0
    )

    scen_em_months = (
        scenario.emergency_months
        if scenario
        else 0.0
    )

    if scenario:

        scen_debt_rem = getattr(
            scenario,
            "remaining_debt",
            getattr(
                scenario,
                "debt_remaining",
                0.0
            )
        )

    else:

        scen_debt_rem = 0.0

    scen_goal_stat = (
        scenario.goal_status
        if scenario
        else "N/A"
    )

    scen_expl = (
        scenario.explanation
        if scenario
        else "N/A"
    )

    # =====================================================
    # 7. BUILD WHAT-IF SCENARIO TEXT
    # =====================================================

    # =====================================================
    # 7. BUILD WHAT-IF SCENARIO TEXT
    # =====================================================

    def _extract_scenario(item):
        if isinstance(item, dict) and "scenario" in item:
            return item["scenario"]
        return item

    def _get_val(obj_or_dict, attr_or_key, default=None):
        if obj_or_dict is None:
            return default
        if isinstance(obj_or_dict, dict):
            return obj_or_dict.get(attr_or_key, default)
        return getattr(obj_or_dict, attr_or_key, default)

    what_if_text = ""

    for item in what_if_scenarios:

        scenario_result = _extract_scenario(item)

        remaining_debt = _get_val(
            scenario_result,
            "remaining_debt",
            _get_val(
                scenario_result,
                "debt_remaining",
                0.0
            )
        )

        emergency_months_result = _get_val(
            scenario_result,
            "emergency_months",
            0.0
        )

        monthly_income_val = _get_val(
            scenario_result,
            "monthly_income",
            0.0
        )

        monthly_expenses_val = _get_val(
            scenario_result,
            "monthly_expenses",
            0.0
        )

        monthly_surplus_val = _get_val(
            scenario_result,
            "monthly_surplus",
            0.0
        )

        debt_payment_val = _get_val(
            scenario_result,
            "debt_payment",
            0.0
        )

        investment_capacity_val = _get_val(
            scenario_result,
            "investment_capacity",
            0.0
        )

        goal_req_val = _get_val(
            scenario_result,
            "goal_monthly_requirement",
            0.0
        )

        goal_shortfall_val = _get_val(
            scenario_result,
            "goal_shortfall",
            None
        )

        if goal_shortfall_val is None:
            goal_shortfall_val = max(
                goal_req_val - monthly_surplus_val,
                0.0
            )

        scenario_name_val = _get_val(
            scenario_result,
            "scenario_name",
            "Unknown Scenario"
        )

        goal_status_val = _get_val(
            scenario_result,
            "goal_status",
            "N/A"
        )

        explanation_val = _get_val(
            scenario_result,
            "explanation",
            ""
        )

        what_if_text += f"""
SCENARIO: {scenario_name_val}

Monthly Income:
₹{monthly_income_val:.2f}

Monthly Expenses:
₹{monthly_expenses_val:.2f}

Monthly Surplus:
₹{monthly_surplus_val:.2f}

Debt Payment:
₹{debt_payment_val:.2f}

Remaining Debt:
₹{remaining_debt:.2f}

Emergency Coverage:
{emergency_months_result:.2f} months

Investment Capacity:
₹{investment_capacity_val:.2f}

Goal Requirement:
₹{goal_req_val:.2f}

Goal Shortfall:
₹{goal_shortfall_val:.2f}

Goal Status:
{goal_status_val}

Scenario Explanation:
{explanation_val}

----------------------------------------
"""

    if not what_if_text:

        what_if_text = (
            "No What-If scenarios are currently available."
        )

    # =====================================================
    # 8. BUILD SCENARIO RANKING CONTEXT
    # =====================================================

    # main.py passes the What-If scenarios in ranking order.
    # Gemini only explains the supplied ranking; it never
    # recalculates or changes scenario scores.

    scenario_ranking_text = ""

    for index, item in enumerate(
        what_if_scenarios,
        start=1
    ):

        scenario_result = _extract_scenario(item)

        rank = _get_val(
            item,
            "rank",
            index
        )

        score = _get_val(
            item,
            "score",
            None
        )

        scenario_name = _get_val(
            scenario_result,
            "scenario_name",
            "Unknown Scenario"
        )

        monthly_surplus = _get_val(
            scenario_result,
            "monthly_surplus",
            0.0
        )

        investment_capacity = _get_val(
            scenario_result,
            "investment_capacity",
            0.0
        )

        goal_status = _get_val(
            scenario_result,
            "goal_status",
            "N/A"
        )

        surplus_change = _get_val(
            scenario_result,
            "surplus_change",
            0.0
        )

        score_text = (
            f"{float(score):.2f}"
            if score is not None
            else "N/A"
        )

        scenario_ranking_text += f"""
Rank: {rank}
Score: {score_text}
Scenario: {scenario_name}
Monthly Surplus: ₹{monthly_surplus:.2f}
Investment Capacity: ₹{investment_capacity:.2f}
Goal Status: {goal_status}
Surplus Change: ₹{surplus_change:.2f}

"""

    if not scenario_ranking_text:
        scenario_ranking_text = (
            "No ranked What-If scenarios are currently available."
        )

    # main.py sends ranked scenarios with Rank 1 first.
    best_item = (
        what_if_scenarios[0]
        if what_if_scenarios
        else None
    )

    best_scenario = (
        _extract_scenario(best_item)
        if best_item
        else None
    )

    best_scenario_name = (
        _get_val(
            best_scenario,
            "scenario_name",
            "N/A"
        )
        if best_scenario
        else "N/A"
    )

    best_scenario_score = (
        _get_val(
            best_item,
            "score",
            None
        )
        if best_item
        else None
    )

    best_scenario_score_text = (
        f"{float(best_scenario_score):.2f}"
        if best_scenario_score is not None
        else "N/A"
    )


    # =====================================================
    # 9. BUILD VERIFIED FINANCIAL CONTEXT
    # =====================================================

    prompt = f"""
Here is the verified financial state produced by the
MoneyBuddy financial engine.

USER FINANCIAL PROFILE

Monthly Income:
₹{user.salary:.2f}

Essential Expenses:
₹{user.essential_expense:.2f}

EMI:
₹{user.emi:.2f}

Outstanding Debt:
₹{user.debt:.2f}

Debt Interest Rate:
{user.interest:.2f}%

Emergency Fund:
₹{user.emergency_fund:.2f}


FINANCIAL HEALTH

Health Score:
{health_advice.score:.1f}/100

Savings Ratio:
{health_advice.metrics.savingratio:.1f}%

Expense Ratio:
{health_advice.metrics.expenseratio:.1f}%

Debt Ratio:
{health_advice.metrics.debtratio:.1f}%


SALARY PLAN

Emergency Fund Allocation:
₹{salary_plan.emergency_fund:.2f}

Debt Payment:
₹{salary_plan.debt_payment:.2f}

Investment Allocation:
₹{salary_plan.investments:.2f}

Goal Savings:
₹{salary_plan.goal_savings:.2f}

Leisure:
₹{salary_plan.leisure:.2f}


GOAL ANALYSIS

Target:
₹{goal_analysis.target_amount:.2f}

Current Amount:
₹{goal_analysis.current_amount:.2f}

Remaining:
₹{goal_analysis.remaining_amount:.2f}

Required Monthly Saving:
₹{goal_analysis.required_monthly_saving:.2f}

Status:
{goal_analysis.status}


MARKET ANALYSIS

Asset:
{market_analysis.symbol}

Current Price:
₹{market_analysis.current_price:.2f}

30-Day Return:
{market_analysis.return_percent:.2f}%

Volatility:
{market_analysis.volatility_percent:.2f}%

Trend:
{market_analysis.trend}

Risk Level:
{market_analysis.risk_level}

Market Signal:
{market_analysis.momentum}


INVESTMENT DECISION

Action:
{investment_decision.action}

Recommended Amount:
₹{investment_decision.recommended_amount:.2f}

Reason:
{investment_decision.reason}

Confidence:
{investment_decision.confidence:.1f}%


PRIORITY DECISIONS

{decision_text}


RISK PROFILE

Risk Capacity:
{risk_capacity}

Risk Tolerance:
{risk_tolerance}

Overall Risk Profile:
{overall_profile}

Emergency Coverage:
{emergency_months:.2f} months

Risk Explanation:
{risk_explanation}


GOAL PRIORITIES

{goal_priorities_text}


PORTFOLIO RECOMMENDATION

Action:
{port_action}

Priority:
{port_priority}

Reason:
{port_reason}


CURRENT SCENARIO

Scenario:
{scen_name}

Monthly Income:
₹{scen_income:.2f}

Monthly Expenses:
₹{scen_expenses:.2f}

Monthly Surplus:
₹{scen_surplus:.2f}

Debt Payment:
₹{scen_debt_pmt:.2f}

Investment Capacity:
₹{scen_inv_cap:.2f}

Emergency Coverage:
{scen_em_months:.2f} months

Projected Debt:
₹{scen_debt_rem:.2f}

Goal Status:
{scen_goal_stat}

Scenario Explanation:
{scen_expl}


WHAT-IF SCENARIO ANALYSIS

The following scenarios were calculated by the
MoneyBuddy Python financial engine.

Do not modify these values.

{what_if_text}


WHAT-IF SCENARIO RANKING

The following ranking was calculated by the
MoneyBuddy Python scenario ranking engine.

Do not recalculate, modify, or invent ranking scores.

{scenario_ranking_text}


BEST SUPPLIED WHAT-IF SCENARIO

Scenario:
{best_scenario_name}

Score:
{best_scenario_score_text}
"""

    # =====================================================
    # 10. ADD AI CFO TASK
    # =====================================================

    prompt += """

TASK

Generate the structured MoneyBuddy CFO response.

The response must:

1. Identify the highest-priority action already determined
   by the MoneyBuddy decision engine.

2. Explain why that priority applies to this user.

3. Include the other existing financial priorities.

4. Explain the investment decision.

5. Explain the user's goal status.

6. Provide practical next steps.

7. Explain what circumstances should trigger a reassessment.

8. Produce a concise personalized message.

9. Consider the supplied What-If scenarios and explain
   their financial trade-offs when relevant.

10. Use the supplied scenario ranking as the source of truth
    when discussing which scenario ranks highest.

11. Identify the supplied Rank 1 scenario as the best-ranked
    What-If scenario. Do not independently recalculate its score.

12. Explain why the Rank 1 scenario is favorable using only
    the supplied scenario values and the existing MoneyBuddy
    priorities.

13. Briefly explain why lower-ranked scenarios are less
    compatible when relevant.

14. Do not change any What-If scenario numbers or ranking scores.

15. Do not create new scenario calculations.

16. Do not treat scenario results as guaranteed future
    outcomes.

IMPORTANT:

Use the supplied allocation amounts exactly.

Do not change:

- Emergency Fund Allocation
- Debt Allocation
- Goal Allocation
- Investment Allocation

The "top_priority.amount" must match the allocated amount
of the highest-priority decision.

The "secondary_priorities" amounts must match the
allocated amounts of the corresponding decisions.

The "investment_amount" must match the
Investment Decision Recommended Amount.

The "goal_status" must match the supplied Goal Analysis
Status.

The "goal_shortfall" must equal the supplied difference
between the required monthly goal contribution and the
currently allocated goal contribution.

Do not create new financial allocations.

Do not override the MoneyBuddy financial engine.

The What-If scenarios are analytical comparisons only.
They must not override the current MoneyBuddy decision.

The scenario ranking is analytical guidance only.
Do not turn it into a new allocation or override the
current MoneyBuddy decision engine.

If scenarios are already ranked, preserve that ranking exactly.

Return ONLY valid JSON.

Do not use Markdown.

Do not use code fences.
"""

    # =====================================================
    # 11. RETURN FINAL PROMPT
    # =====================================================

    return prompt